apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: vanilla-oss-gateway
build:
  artifacts:
  - image: albertoimpl/vanilla-oss-gateway
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
