apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-oss-gateway-deployment
spec:
  selector:
    matchLabels:
      app: vanilla-oss-gateway
  template:
    metadata:
      labels:
        app: vanilla-oss-gateway
    spec:
      containers:
        - name: vanilla-oss-gateway
          image: albertoimpl/vanilla-oss-gateway
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
