apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-cloud-gateway.fullname" . }}
  labels:
    {{- include "spring-cloud-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "spring-cloud-gateway.selectorLabels" . | nindent 4 }}
